version: '3.8'

services:
  backend:
    build: .
    container_name: nestjs_ecommerce
    restart: always
    ports:
      - '3000:3000'
    depends_on:
      - mysql
      - redis
    env_file:
      - .env

  mysql:
    image: mysql:8
    container_name: mysql_db
    restart: always
    ports:
      - '3307:3306'
    env_file:
      - .env
    volumes:
      - mysql_data:/var/lib/mysql

  redis:
    image: redis:latest
    container_name: redis_cache
    restart: always
    ports:
      - '6379:6379'

volumes:
  mysql_data:
